# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc5f014745e89190e9ea92934e43a8e66db950d34306bf065b1d178d754160d511d0552b107c5cfc87f9bb2b6341503a8afb5b10c88a9b37f0f675ce0be9adc1

test:
  secret_key_base: 506099631231f4972148949a9448e5ff12e835282b8117a716dd3fe5880fe99c279f56f654bf8c56bcf915c824bd527a89b89ceceea86cfd8bddaa4a8e3979aa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
